import { MasterDatasetKey } from '../../types/masterDataset';

/** Maps master dataset keys to upstream field labels (priority order). */
export const MASTER_FIELD_SOURCE_ALIASES: Record<MasterDatasetKey, string[]> = {
  tenderNumber: ['Tender Number', 'tenderNumber', 'tenderReferenceNumber'],
  nitNumber: ['NIT Number', 'nitNumber'],
  bidReferenceNumber: ['Bid Reference No', 'Tender Number', 'tenderReferenceNumber', 'Reference Number'],
  department: ['Department', 'department'],
  organization: ['Organization', 'organization', 'issuingAuthority', 'Tender Authority'],
  tenderTitle: ['Tender Name', 'tenderName', 'Tender Title', 'Title of Tender'],
  workName: ['Name of Work', 'Work Name', 'Work Title', 'Nature of Work'],
  location: ['Work Location', 'workLocation', 'location', 'Place of Work'],
  district: ['District', 'district'],
  state: ['State', 'state'],
  country: ['Country', 'country', 'India'],
  estimatedCost: ['Tender Value', 'estimatedTenderValue', 'Estimated Cost', 'estimatedCost'],
  tenderValue: ['Tender Value', 'estimatedTenderValue', 'estimatedCost'],
  emdAmount: ['EMD', 'emdAmount', 'Earnest Money Deposit'],
  documentFee: ['Tender Fee', 'tenderFee', 'Document Fee', 'documentFee'],
  publishingDate: ['Tender Publish Date', 'tenderPublishDate', 'Publish Date', 'publishingDate'],
  bidStartDate: ['Submission Start Date', 'bidSubmissionStartDate', 'Bid Start Date'],
  bidEndDate: ['Bid Submission Date', 'bidSubmissionDate', 'Bid End Date', 'Submission End Date'],
  technicalBidDate: ['Technical Bid Date', 'technicalBidOpeningDate', 'Technical Bid Opening'],
  financialBidDate: ['Financial Bid Date', 'financialBidOpeningDate', 'Financial Bid Opening'],
  preBidMeetingDate: ['Pre-Bid Meeting Date', 'preBidMeetingDate', 'Pre Bid Meeting'],
  contactName: ['Contact Name', 'contactName', 'Name of Contact'],
  contactDesignation: ['Contact Designation', 'contactDesignation', 'Designation'],
  contactEmail: ['Contact Email', 'contactEmail', 'Email'],
  contactPhone: ['Contact Phone', 'contactPhone', 'Phone', 'Mobile'],
  eligibilityCriteria: ['Eligibility', 'eligibilityCriteria', 'Eligibility Criteria'],
  experienceRequirement: ['Experience', 'experienceRequirements', 'Experience Requirement'],
  turnoverRequirement: ['Turnover', 'turnoverRequirements', 'Turnover Requirement'],
  manpowerRequirement: ['Manpower', 'manpowerRequirement', 'Manpower Requirement'],
  equipmentRequirement: ['Equipment', 'equipmentRequirement', 'Equipment Requirement'],
  completionPeriod: ['Contract Duration', 'contractDuration', 'Completion Period'],
  contractPeriod: ['Contract Duration', 'contractDuration', 'Contract Period'],
  performanceSecurity: ['Performance Security', 'performanceSecurity', 'Bank Guarantee'],
  paymentTerms: ['Payment Terms', 'paymentTerms'],
  penaltyClauses: ['Penalty', 'penaltyClauses', 'Liquidated Damages'],
  certificates: ['Required Documents', 'requiredDocuments', 'Certificates', 'GST Requirement'],
  scopeOfWork: ['Scope of Work', 'scopeOfWork', 'Description of Work'],
};

/** Bid Dates composite field sub-label → master date key */
export const BID_DATE_SUBLABEL_MAP: Record<string, MasterDatasetKey> = {
  'bid start date': 'bidStartDate',
  'submission start date': 'bidStartDate',
  'bid end date': 'bidEndDate',
  'bid submission date': 'bidEndDate',
  'submission end date': 'bidEndDate',
  'last date': 'bidEndDate',
  'technical bid date': 'technicalBidDate',
  'technical bid opening': 'technicalBidDate',
  'financial bid date': 'financialBidDate',
  'financial bid opening': 'financialBidDate',
  'pre-bid meeting date': 'preBidMeetingDate',
  'pre bid meeting date': 'preBidMeetingDate',
  'prebid meeting date': 'preBidMeetingDate',
};
