import { SERVICE_CLASSIFICATION_KNOWLEDGE_BASE } from './serviceClassificationKnowledgeBase';

/** @deprecated Use SERVICE_CLASSIFICATION_KNOWLEDGE_BASE directly */
export const TENDER_SERVICE_CLASSIFICATION_CATALOG = SERVICE_CLASSIFICATION_KNOWLEDGE_BASE;
