import { ProductionFieldDefinition } from './fieldDefinitions';
import { DATE, MONEY } from './fieldDefinitions';

/** Additional production fields for enterprise NIT coverage. */
export const ENTERPRISE_PRODUCTION_FIELDS: ProductionFieldDefinition[] = [
  {
    id: 'issuingAuthority',
    label: 'Tender Authority',
    mergeKey: 'issuingAuthority',
    section: 'general',
    valueType: 'text',
    labels: ['tendering authority', 'issuing authority', 'employer', 'owner'],
    patterns: [
      /(?:tendering|issuing)\s+authority[:\s]+([^\n]{3,150})/i,
      /(?:name\s+of\s+(?:authority|employer))[:\s]+([^\n]{3,150})/i,
    ],
    pageHints: ['authority', 'nit', 'employer'],
    maxLength: 150,
  },
  {
    id: 'tenderCategory',
    label: 'Tender Category',
    mergeKey: 'tenderCategory',
    section: 'general',
    valueType: 'text',
    labels: ['tender category', 'category of tender', 'type of procurement'],
    patterns: [/(?:tender\s+category|category)[:\s]+([^\n]{3,80})/i],
    pageHints: ['category', 'nit'],
    maxLength: 80,
  },
  {
    id: 'tenderType',
    label: 'Tender Type',
    mergeKey: 'tenderType',
    section: 'general',
    valueType: 'text',
    labels: ['tender type', 'mode of tender', 'nature of tender'],
    patterns: [
      /(?:tender\s+type|mode\s+of\s+tender)[:\s]+([^\n]{3,80})/i,
      /(open\s+tender|limited\s+tender|e-?tender|two\s+bid\s+system|single\s+stage)/i,
    ],
    pageHints: ['tender type', 'nit'],
    maxLength: 80,
  },
  {
    id: 'tenderPublishDate',
    label: 'Tender Publish Date',
    mergeKey: 'tenderPublishDate',
    section: 'timeline',
    valueType: 'date',
    labels: ['publish date', 'date of publication', 'nit date', 'tender publish'],
    patterns: [
      /(?:publish|publication)\s+date[^:\n]{0,40}[:\s]+(\d{1,2}[/.-]\d{1,2}[/.-]\d{2,4})/i,
    ],
    pageHints: ['publish', 'nit', 'date'],
    maxLength: 60,
  },
  {
    id: 'bidSubmissionStartDate',
    label: 'Submission Start Date',
    mergeKey: 'bidSubmissionStartDate',
    section: 'timeline',
    valueType: 'date',
    labels: ['bid submission start', 'start date of submission', 'opening of bid'],
    patterns: [
      /(?:submission\s+start|start\s+date\s+of\s+(?:bid|submission))[^:\n]{0,40}[:\s]+(\d{1,2}[/.-]\d{1,2}[/.-]\d{2,4})/i,
    ],
    pageHints: ['submission', 'schedule', 'date'],
    maxLength: 60,
  },
  {
    id: 'clarificationEndDate',
    label: 'Clarification End Date',
    mergeKey: 'importantDates',
    section: 'timeline',
    valueType: 'date',
    labels: ['clarification', 'query', 'pre-bid query', 'last date for clarification'],
    patterns: [
      /(?:clarification|query)[^:\n]{0,40}(?:last\s+date|end\s+date)[^:\n]{0,20}[:\s]+(\d{1,2}[/.-]\d{1,2}[/.-]\d{2,4})/i,
    ],
    pageHints: ['clarification', 'query', 'pre-bid'],
    maxLength: 60,
  },
  {
    id: 'technicalBidOpeningDate',
    label: 'Technical Bid Opening',
    mergeKey: 'technicalBidOpeningDate',
    section: 'timeline',
    valueType: 'date',
    labels: ['technical bid opening', 'opening of technical bid'],
    patterns: [
      /technical\s+bid\s+opening[^:\n]{0,40}[:\s]+(\d{1,2}[/.-]\d{1,2}[/.-]\d{2,4})/i,
    ],
    pageHints: ['technical', 'opening'],
    maxLength: 60,
  },
  {
    id: 'financialBidOpeningDate',
    label: 'Financial Bid Opening',
    mergeKey: 'financialBidOpeningDate',
    section: 'timeline',
    valueType: 'date',
    labels: ['financial bid opening', 'opening of financial bid', 'price bid opening'],
    patterns: [
      /financial\s+bid\s+opening[^:\n]{0,40}[:\s]+(\d{1,2}[/.-]\d{1,2}[/.-]\d{2,4})/i,
    ],
    pageHints: ['financial', 'opening'],
    maxLength: 60,
  },
  {
    id: 'contractStartDate',
    label: 'Contract Start Date',
    mergeKey: 'importantDates',
    section: 'timeline',
    valueType: 'date',
    labels: ['contract start', 'commencement date', 'start of work'],
    patterns: [
      /(?:contract\s+start|commencement\s+date|start\s+of\s+work)[^:\n]{0,40}[:\s]+(\d{1,2}[/.-]\d{1,2}[/.-]\d{2,4})/i,
    ],
    pageHints: ['contract', 'commencement'],
    maxLength: 60,
  },
  {
    id: 'paymentTerms',
    label: 'Payment Terms',
    mergeKey: 'paymentTerms',
    section: 'financial',
    valueType: 'text',
    labels: ['payment terms', 'mode of payment', 'payment schedule'],
    patterns: [
      /(?:payment\s+terms|mode\s+of\s+payment)[:\s]+([^\n]{8,200})/i,
    ],
    pageHints: ['payment', 'commercial', 'financial'],
    maxLength: 200,
  },
  {
    id: 'securityDeposit',
    label: 'Security Deposit',
    mergeKey: 'performanceSecurity',
    section: 'financial',
    valueType: 'money',
    labels: ['security deposit', 'contract security'],
    patterns: [
      /security\s+deposit[^₹%\d]{0,40}([\d.,]+\s*%|(?:Rs\.?|₹)\s*[\d,]+)/i,
    ],
    pageHints: ['security', 'deposit'],
    maxLength: 100,
  },
  {
    id: 'estimatedCost',
    label: 'Estimated Cost',
    mergeKey: 'estimatedTenderValue',
    section: 'financial',
    valueType: 'money',
    labels: ['estimated cost', 'approximate cost', 'cost estimate'],
    patterns: [
      /(?:estimated\s+cost|approximate\s+cost)[^₹\d]{0,40}((?:Rs\.?|INR|₹)?\s*[\d,]+(?:\.\d+)?(?:\s*(?:Cr|Lakh))?)/i,
    ],
    pageHints: ['cost', 'estimate', 'financial'],
    maxLength: 80,
  },
  {
    id: 'panRequirement',
    label: 'PAN Requirement',
    mergeKey: 'registrationsRequired',
    section: 'eligibility',
    valueType: 'text',
    labels: ['pan', 'permanent account number'],
    patterns: [/(?:valid\s+)?pan(?:\s+card)?(?:\s+registration)?/i],
    pageHints: ['pan', 'document', 'eligibility'],
    maxLength: 60,
  },
  {
    id: 'netWorthRequirement',
    label: 'Net Worth Requirement',
    mergeKey: 'financialRequirements',
    section: 'eligibility',
    valueType: 'text',
    labels: ['net worth', 'networth', 'minimum net worth'],
    patterns: [
      /(?:net\s+worth|networth)[^:\n]{0,40}[:\s]+([^\n]{5,120})/i,
      /(?:minimum\s+net\s+worth)[^:\n]{0,30}[:\s]+([^\n]{5,120})/i,
    ],
    pageHints: ['eligibility', 'financial'],
    maxLength: 120,
  },
  {
    id: 'msmeRequirement',
    label: 'MSME Requirement',
    mergeKey: 'certificationsRequired',
    section: 'eligibility',
    valueType: 'text',
    labels: ['msme', 'udyam', 'small enterprise'],
    patterns: [/(?:msme|udyam)[^:\n]{0,30}(?:registration|certificate)/i],
    pageHints: ['msme', 'udyam', 'eligibility'],
    maxLength: 80,
  },
  {
    id: 'startupRequirement',
    label: 'Startup Requirement',
    mergeKey: 'certificationsRequired',
    section: 'eligibility',
    valueType: 'text',
    labels: ['startup', 'dpiit startup'],
    patterns: [/(?:startup|dpiit)[^:\n]{0,40}(?:registration|recognition)/i],
    pageHints: ['startup', 'eligibility'],
    maxLength: 80,
  },
  {
    id: 'oemRequirement',
    label: 'OEM Requirement',
    mergeKey: 'complianceRequirements',
    section: 'eligibility',
    valueType: 'text',
    labels: ['oem', 'original equipment manufacturer', 'authorized dealer'],
    patterns: [
      /(?:oem|original\s+equipment\s+manufacturer|authorized\s+dealer|manufacturer\s+authorization)/i,
    ],
    pageHints: ['oem', 'technical', 'eligibility'],
    maxLength: 100,
  },
  {
    id: 'mafRequired',
    label: 'MAF Required',
    mergeKey: 'complianceRequirements',
    section: 'general',
    valueType: 'text',
    labels: ['maf', 'manufacturer authorization form'],
    patterns: [
      /maf[^:\n]{0,20}(?:required|applicable|yes|no)/i,
      /manufacturer\s+authorization\s+form/i,
    ],
    pageHints: ['maf', 'oem'],
    maxLength: 40,
  },
  {
    id: 'bidSystem',
    label: 'Bid System',
    mergeKey: 'submissionMode',
    section: 'general',
    valueType: 'text',
    labels: ['bid system', 'two bid system', 'single stage', 'two envelope'],
    patterns: [
      /(two\s+(?:bid|envelope)\s+system|single\s+stage|two\s+stage|e-?tender\s+system)/i,
    ],
    pageHints: ['bid', 'system', 'nit'],
    maxLength: 80,
  },
  {
    id: 'statutoryRequirements',
    label: 'Statutory Requirements',
    mergeKey: 'statutoryRequirements',
    section: 'compliance',
    valueType: 'list',
    labels: ['statutory', 'statutory compliance', 'statutory requirement'],
    patterns: [],
    pageHints: ['statutory', 'compliance', 'legal'],
    maxLength: 200,
    listMaxItems: 10,
  },
  {
    id: 'contractualRequirements',
    label: 'Contractual Requirements',
    mergeKey: 'complianceRequirements',
    section: 'compliance',
    valueType: 'list',
    labels: ['contractual', 'contract conditions', 'special conditions'],
    patterns: [],
    pageHints: ['contract', 'condition', 'compliance'],
    maxLength: 200,
    listMaxItems: 10,
  },
  {
    id: 'legalRequirements',
    label: 'Legal Requirements',
    mergeKey: 'complianceRequirements',
    section: 'compliance',
    valueType: 'list',
    labels: ['legal', 'legal compliance', 'applicable laws'],
    patterns: [],
    pageHints: ['legal', 'law', 'compliance'],
    maxLength: 200,
    listMaxItems: 10,
  },
];

export { MONEY, DATE };
