import { MasterDatasetKey } from '../../types/masterDataset';

/** Primary tender fields shown first in NIT / tender UI tables. */
export const NIT_TENDER_PARAMETER_ORDER: MasterDatasetKey[] = [
  'tenderNumber',
  'nitNumber',
  'bidReferenceNumber',
  'tenderTitle',
  'workName',
  'scopeOfWork',
  'organization',
  'department',
  'location',
  'district',
  'state',
  'emdAmount',
  'tenderValue',
  'estimatedCost',
  'documentFee',
  'publishingDate',
  'bidStartDate',
  'bidEndDate',
  'technicalBidDate',
  'financialBidDate',
  'preBidMeetingDate',
  'contractPeriod',
  'completionPeriod',
  'eligibilityCriteria',
  'experienceRequirement',
  'turnoverRequirement',
  'manpowerRequirement',
  'equipmentRequirement',
  'contactName',
  'contactDesignation',
  'contactEmail',
  'contactPhone',
  'paymentTerms',
  'penaltyClauses',
  'performanceSecurity',
  'certificates',
];
