import { MasterAliasRegistryEntry } from '../../types/enterpriseTenderAlias';

/**
 * Enterprise Master Alias Registry — single source of truth.
 * Add aliases here without code changes elsewhere.
 */
export const MASTER_ALIAS_REGISTRY: MasterAliasRegistryEntry[] = [
  // ── Identity ──────────────────────────────────────────────────────────────
  {
    standardParameter: 'Organization',
    canonicalKey: 'organization',
    category: 'Identity',
    priority: 100,
    aliases: [
      'Organization',
      'Organisation',
      'Tender Inviting Authority',
      'Employer',
      'Purchaser',
      'Issuing Authority',
      'Tender Authority',
      'Procuring Entity',
      'Buyer',
      'Name of Organization',
    ],
    semanticTokens: ['employer', 'purchaser', 'authority', 'inviting', 'procuring', 'organization', 'organisation'],
    patterns: [
      /\b(tender\s*inviting\s*authority|issuing\s*authority|tender\s*authority|employer|purchaser|procuring\s*entity)\b/i,
    ],
  },
  {
    standardParameter: 'Tender Number',
    canonicalKey: 'tenderNumber',
    category: 'Identity',
    priority: 95,
    aliases: ['Tender Number', 'Tender No', 'Tender ID', 'Bid Number', 'Bid No', 'E-Tender No', 'Tender Ref'],
    patterns: [/\b(tender|bid|e-tender)\s*(no\.?|number|id|ref)\b/i],
  },
  {
    standardParameter: 'NIT Number',
    canonicalKey: 'nitNumber',
    category: 'Identity',
    priority: 95,
    aliases: ['NIT Number', 'NIT No', 'Notice Inviting Tender No'],
    patterns: [/\bnit\s*(number|no\.?)\b/i],
  },
  {
    standardParameter: 'Department',
    canonicalKey: 'department',
    category: 'Identity',
    priority: 80,
    aliases: ['Department', 'Dept', 'Name of Department'],
    patterns: [/\b(department|dept\.?)\b/i],
  },
  {
    standardParameter: 'Tender Title',
    canonicalKey: 'tenderTitle',
    category: 'Identity',
    priority: 80,
    aliases: ['Tender Title', 'Tender Name', 'Title of Tender'],
    patterns: [/\b(tender\s*(title|name)|title\s*of\s*tender)\b/i],
  },
  {
    standardParameter: 'Name Of Work',
    canonicalKey: 'workName',
    category: 'Identity',
    priority: 85,
    aliases: ['Name Of Work', 'Name of the Work', 'Work Name', 'Nature of Work', 'Subject of Tender'],
    patterns: [/\b(name\s*of\s*(the\s*)?work|nature\s*of\s*work|work\s*(name|title))\b/i],
  },
  {
    standardParameter: 'Location',
    canonicalKey: 'location',
    category: 'Identity',
    priority: 75,
    aliases: ['Location', 'Work Location', 'Site Location', 'Place of Work'],
    patterns: [/\b(work\s*)?location\b/i],
  },

  // ── Financial ─────────────────────────────────────────────────────────────
  {
    standardParameter: 'Tender Value',
    canonicalKey: 'tenderValue',
    category: 'Financial',
    priority: 100,
    aliases: [
      'Tender Value',
      'Estimated Cost',
      'Estimated Tender Value',
      'Tender Cost',
      'Project Cost',
      'Contract Value',
      'Work Value',
      'Estimated Project Cost',
      'Tender Amount',
      'Value of Work',
      'Approximate Value',
      'Approximate Cost',
      'Cost of Work',
      'Estimated Cost of Work',
    ],
    semanticTokens: ['tender', 'value', 'cost', 'project', 'contract', 'estimated', 'work'],
    patterns: [
      /\b(tender\s*(value|cost|amount)|contract\s*value|project\s*cost|estimated\s*cost|work\s*value)\b/i,
      /\bvalue\s*of\s*work\b/i,
      /\bestimated\s*(tender\s*)?value\b/i,
      /\b(approximate|estimated)\s+cost\s+of\s+work\b/i,
    ],
  },
  {
    standardParameter: 'EMD Amount',
    canonicalKey: 'emdAmount',
    category: 'Financial',
    priority: 100,
    aliases: [
      'EMD',
      'EMD Amount',
      'Earnest Money Deposit',
      'Earnest Money',
      'Bid Security',
      'Bid Security Amount',
      'Security Deposit For Bid',
      'Bid Earnest Money',
      'EMD Value',
      'Earnest Money Deposit Amount',
    ],
    semanticTokens: ['emd', 'earnest', 'money', 'deposit', 'bid', 'security'],
    patterns: [
      /\b(emd|earnest\s*money(\s*deposit)?|bid\s*security(\s*amount)?|security\s*deposit\s*for\s*bid|bid\s*earnest\s*money)\b/i,
    ],
  },
  {
    standardParameter: 'Tender Fee',
    canonicalKey: 'documentFee',
    category: 'Financial',
    priority: 90,
    aliases: [
      'Tender Fee',
      'Document Fee',
      'Bid Fee',
      'Processing Fee',
      'Tender Processing Fee',
      'Cost Of Tender',
      'Cost of Tender',
      'Cost of Tender Document',
    ],
    patterns: [/\b(tender\s*(document\s*)?fee|document\s*fee|bid\s*fee|processing\s*fee|cost\s*of\s*tender)\b/i],
  },
  {
    standardParameter: 'Performance Security',
    canonicalKey: 'performanceSecurity',
    category: 'Financial',
    priority: 90,
    aliases: [
      'Performance Security',
      'Performance Guarantee',
      'PBG',
      'Performance Bank Guarantee',
      'Performance Bond',
    ],
    patterns: [/\bperformance\s*(security|guarantee|bond|bank\s*guarantee|bg)\b/i, /\bpbg\b/i],
  },
  {
    standardParameter: 'Bank Guarantee',
    canonicalKey: 'bankGuarantee',
    category: 'Financial',
    priority: 85,
    aliases: ['Bank Guarantee', 'BG Amount', 'Security Deposit BG'],
    patterns: [/\bbank\s*guarantee\b/i],
  },
  // ── Timeline ──────────────────────────────────────────────────────────────
  {
    standardParameter: 'Bid Start Date',
    canonicalKey: 'bidStartDate',
    category: 'Timeline',
    priority: 95,
    aliases: [
      'Bid Start Date',
      'Bid Submission Start',
      'Submission Start Date',
      'Tender Start Date',
      'Start Date of Bid',
      'Bid Commencement Date',
    ],
    patterns: [/\b(bid\s*(start|commencement)|submission\s*start|tender\s*start)\b/i],
  },
  {
    standardParameter: 'Bid End Date',
    canonicalKey: 'bidEndDate',
    category: 'Timeline',
    priority: 100,
    aliases: [
      'Bid End Date',
      'Bid Submission End',
      'Submission End Date',
      'Submission Deadline',
      'Tender Closing Date',
      'Last Date Of Submission',
      'Closing Date',
      'Due Date',
      'Bid Closing Date',
      'Bid Due Date',
    ],
    patterns: [
      /\b(bid\s*(end|closing|due)|last\s*date\s*of\s*submission|closing\s*date|due\s*date|submission\s*(deadline|end))\b/i,
    ],
  },
  {
    standardParameter: 'Technical Bid Opening Date',
    canonicalKey: 'technicalBidDate',
    category: 'Timeline',
    priority: 90,
    aliases: [
      'Technical Opening',
      'Technical Bid Opening',
      'Tech Bid Opening',
      'Technical Evaluation Date',
      'Technical Bid Opening Date',
      'Technical Opening Date',
    ],
    patterns: [/\btechnical\s*(bid\s*)?(opening|open|evaluation)(\s*date)?\b/i],
  },
  {
    standardParameter: 'Financial Bid Opening Date',
    canonicalKey: 'financialBidDate',
    category: 'Timeline',
    priority: 90,
    aliases: [
      'Financial Opening',
      'Financial Bid Opening',
      'Price Bid Opening',
      'Commercial Bid Opening',
      'Financial Bid Opening Date',
      'Financial Opening Date',
    ],
    patterns: [/\b(financial|price|commercial)\s*(bid\s*)?(opening|open)(\s*date)?\b/i],
  },
  {
    standardParameter: 'Publishing Date',
    canonicalKey: 'publishingDate',
    category: 'Timeline',
    priority: 85,
    aliases: ['Publishing Date', 'Publish Date', 'Date of Publication'],
    patterns: [/\b(publish(ing|ed)?\s*date|date\s*of\s*publication)\b/i],
  },
  {
    standardParameter: 'Pre Bid Meeting Date',
    canonicalKey: 'preBidMeetingDate',
    category: 'Timeline',
    priority: 80,
    aliases: ['Pre Bid Meeting Date', 'Pre-Bid Meeting', 'Pre Bid Meeting', 'Prebid Meeting Date'],
    patterns: [/\bpre[\s-]?bid\s*meeting(\s*date)?\b/i],
  },
  {
    standardParameter: 'Completion Period',
    canonicalKey: 'completionPeriod',
    category: 'Timeline',
    priority: 85,
    aliases: ['Completion Period', 'Time for Completion', 'Period of Completion'],
    patterns: [/\b(completion\s*(period|time)|time\s*for\s*completion)\b/i],
  },
  {
    standardParameter: 'Contract Period',
    canonicalKey: 'contractPeriod',
    category: 'Timeline',
    priority: 80,
    aliases: ['Contract Period', 'Agreement Period', 'Period of Contract'],
    patterns: [/\b(contract|agreement)\s*(period|duration)\b/i],
  },

  // ── Eligibility ───────────────────────────────────────────────────────────
  {
    standardParameter: 'Turnover Requirement',
    canonicalKey: 'turnoverRequirement',
    category: 'Eligibility',
    priority: 95,
    aliases: [
      'Turnover',
      'Turnover Requirement',
      'Annual Turnover',
      'Average Annual Turnover',
      'Minimum Turnover',
      'Financial Turnover',
      'Financial Capacity',
    ],
    semanticTokens: ['turnover', 'annual', 'financial', 'minimum'],
    patterns: [
      /\b(turnover\s*requirement|annual\s*turnover|minimum\s*turnover|average\s*annual\s*turnover)\b/i,
      /\bfinancial\s*capacity\b.*\bturnover\b/i,
      /\bturnover\b.*\bfinancial\s*capacity\b/i,
    ],
  },
  {
    standardParameter: 'Experience Requirement',
    canonicalKey: 'experienceRequirement',
    category: 'Eligibility',
    priority: 95,
    aliases: [
      'Experience',
      'Experience Requirement',
      'Past Experience',
      'Similar Work Experience',
      'Work Experience',
      'Relevant Experience',
    ],
    semanticTokens: ['experience', 'similar', 'work', 'past', 'relevant'],
    patterns: [/\b(experience\s*requirement|similar\s*work\s*experience|past\s*experience|work\s*experience)\b/i],
  },
  {
    standardParameter: 'Net Worth Requirement',
    canonicalKey: 'netWorthRequirement',
    category: 'Eligibility',
    priority: 85,
    aliases: ['Net Worth Requirement', 'Minimum Net Worth', 'Net Worth'],
    patterns: [/\bnet\s*worth(\s*requirement)?\b/i],
  },
  {
    standardParameter: 'Bid Capacity',
    canonicalKey: 'bidCapacity',
    category: 'Eligibility',
    priority: 80,
    aliases: ['Bid Capacity', 'Financial Capacity', 'Monetary Capacity'],
    patterns: [/\b(bid\s*capacity|financial\s*capacity)\b/i],
  },

  // ── Compliance ────────────────────────────────────────────────────────────
  {
    standardParameter: 'GST',
    canonicalKey: 'gst',
    category: 'Compliance',
    priority: 90,
    aliases: [
      'GST',
      'GST Requirement',
      'GST Registration',
      'GST Certificate',
      'GSTIN',
      'Goods And Services Tax Registration',
      'Goods and Services Tax Registration',
    ],
    patterns: [/\bgst(in)?(\s*(registration|certificate|requirement))?\b/i, /\bgoods\s+and\s+services\s+tax\b/i],
  },
  {
    standardParameter: 'PAN',
    canonicalKey: 'pan',
    category: 'Compliance',
    priority: 90,
    aliases: [
      'PAN',
      'PAN Requirement',
      'PAN Card',
      'Permanent Account Number',
      'PAN Number',
      'Company PAN',
    ],
    patterns: [/\bpan(\s*(card|no\.?|number|requirement|permanent\s*account|company))?\b/i],
  },
  {
    standardParameter: 'MSME',
    canonicalKey: 'msme',
    category: 'Compliance',
    priority: 85,
    aliases: [
      'MSME',
      'MSE',
      'MSME Requirement',
      'Udyam',
      'Udyam Registration',
      'Micro Small Medium Enterprise',
      'Small Enterprise',
    ],
    patterns: [/\b(msme|mse|udyam|micro\s*small\s*medium)\b/i],
  },
  {
    standardParameter: 'ISO Requirement',
    canonicalKey: 'iso',
    category: 'Compliance',
    priority: 80,
    aliases: ['ISO', 'ISO Requirement', 'ISO Certification', 'ISO 9001'],
    patterns: [/\biso(\s*\d+)?(\s*(certification|requirement))?\b/i],
  },
  {
    standardParameter: 'EPF',
    canonicalKey: 'pf',
    category: 'Compliance',
    priority: 85,
    tenderTypes: ['Manpower'],
    aliases: [
      'EPF',
      'PF',
      'PF Requirement',
      'Provident Fund',
      'PF Registration',
      'Employees Provident Fund',
      'Employee Provident Fund',
    ],
    patterns: [/\b(epf|pf|provident\s*fund|employees?\s*provident\s*fund)(\s*requirement|\s*registration)?\b/i],
  },
  {
    standardParameter: 'ESIC',
    canonicalKey: 'esic',
    category: 'Compliance',
    priority: 85,
    tenderTypes: ['Manpower'],
    aliases: [
      'ESIC',
      'ESIC Requirement',
      'ESI',
      'Employees State Insurance',
      'Employee State Insurance',
      'ESIC Registration',
    ],
    patterns: [/\b(esic|esi)(\s*requirement|\s*registration)?\b/i, /\bemployees?\s*state\s*insurance\b/i],
  },
  {
    standardParameter: 'Labour License Requirement',
    canonicalKey: 'labourLicense',
    category: 'Compliance',
    priority: 75,
    aliases: ['Labour License', 'Labor License', 'Contract Labour License', 'Labour License Requirement'],
    patterns: [/\b(labou?r)\s*licen[cs]e(\s*requirement)?\b/i],
  },
  {
    standardParameter: 'Bank Solvency Requirement',
    canonicalKey: 'bankSolvency',
    category: 'Compliance',
    priority: 75,
    aliases: ['Bank Solvency', 'Bank Solvency Requirement', 'Solvency Certificate', 'Financial Solvency'],
    patterns: [/\b(bank\s*)?solvency(\s*(certificate|requirement))?\b/i],
  },

  // ── Manpower ────────────────────────────────────────────────────────────────
  {
    standardParameter: 'Payroll Strength',
    category: 'Eligibility',
    priority: 88,
    tenderTypes: ['Manpower'],
    aliases: [
      'Payroll Strength',
      'Employee Strength',
      'Minimum Employees',
      'Staff Strength',
      'Manpower Strength',
      'Minimum Manpower',
      'Number of Employees',
    ],
    patterns: [
      /\b(payroll|employee|staff|manpower)\s*strength\b/i,
      /\bminimum\s*(employees|manpower|staff)\b/i,
      /\bnumber\s+of\s+employees\b/i,
    ],
  },

  // ── Service-specific (dynamic standard names) ───────────────────────────────
  {
    standardParameter: 'PSARA License',
    category: 'Compliance',
    serviceCategories: ['Security Services'],
    tenderTypes: ['Security'],
    priority: 90,
    aliases: [
      'PSARA',
      'PSARA License',
      'PSARA Licence',
      'Private Security Agency License',
      'Security Agency License',
      'Private Security License',
    ],
    patterns: [
      /\bpsara(\s*licen[cs]e)?\b/i,
      /\bprivate\s*security\s*agency\s*licen[cs]e\b/i,
      /\bsecurity\s*agency\s*licen[cs]e\b/i,
    ],
  },
  {
    standardParameter: 'Manpower License',
    category: 'Compliance',
    serviceCategories: ['Manpower Services'],
    priority: 85,
    aliases: ['Labour License', 'Contract Labour License', 'Manpower License', 'Labor License'],
    patterns: [/\b(contract\s*labou?r\s*licen[cs]e|manpower\s*licen[cs]e)\b/i],
  },
  {
    standardParameter: 'AMC Duration',
    category: 'Timeline',
    serviceCategories: ['Facility Management'],
    priority: 75,
    aliases: ['AMC', 'Annual Maintenance Contract', 'Maintenance Contract', 'AMC Duration', 'AMC Period'],
    patterns: [/\b(amc|annual\s*maintenance\s*contract|maintenance\s*contract)(\s*(duration|period))?\b/i],
  },

  // ── Scope / Technical ───────────────────────────────────────────────────────
  {
    standardParameter: 'Scope Of Work',
    canonicalKey: 'scopeOfWork',
    category: 'Scope',
    priority: 85,
    aliases: ['Scope Of Work', 'Scope of the Work', 'Work Scope'],
    patterns: [/\bscope\s*of\s*(the\s*)?work\b/i],
  },
  {
    standardParameter: 'Technical Requirements',
    canonicalKey: 'technicalRequirements',
    category: 'Technical',
    priority: 85,
    aliases: ['Technical Requirements', 'Technical Specification', 'Technical Specs'],
    patterns: [/\btechnical\s*(requirements?|specifications?|specs?)\b/i],
  },
  {
    standardParameter: 'BG Required',
    canonicalKey: 'bgRequired',
    category: 'Financial',
    priority: 70,
    aliases: ['BG Required', 'Bank Guarantee Required', 'BG Applicable'],
    patterns: [/\b(bg|bank\s*guarantee)\s*(is\s*)?(required|applicable)\b/i],
  },
  {
    standardParameter: 'OEM Authorization',
    category: 'Tender Specific',
    serviceCategories: ['IT Services', 'Supply Tenders'],
    tenderTypes: ['IT', 'Supply', 'GeM', 'Procurement'],
    priority: 88,
    aliases: [
      'OEM Authorization',
      'OEM Authorisation',
      'OEM Certificate',
      'Manufacturer Authorization',
      'Manufacturer Authorisation',
      'Authorization Letter',
      'Authorisation Letter',
    ],
    patterns: [
      /\boem\s*(authorization|authorisation|certificate)\b/i,
      /\bmanufacturer\s*(authorization|authorisation)(\s*letter|\s*certificate)?\b/i,
      /\bauthorization\s*letter\b/i,
    ],
  },
  {
    standardParameter: 'MAF',
    category: 'Tender Specific',
    serviceCategories: ['IT Services', 'Supply Tenders'],
    tenderTypes: ['IT', 'Supply', 'GeM', 'Procurement'],
    priority: 88,
    aliases: [
      'MAF',
      'MAF Certificate',
      'Manufacturer Authorization Form',
      'Manufacturer Authorisation Form',
      'Manufacturer Support Letter',
      'MAF Requirement',
    ],
    patterns: [
      /\bmaf(\s*(certificate|requirement))?\b/i,
      /\bmanufacturer\s*authorization\s*form\b/i,
      /\bmanufacturer\s*support\s*letter\b/i,
    ],
  },
  {
    standardParameter: 'MAF Required',
    canonicalKey: 'mafRequired',
    category: 'Technical',
    priority: 70,
    aliases: ['MAF Required', 'MAF Applicable'],
    patterns: [/\bmaf\s*(is\s*)?(required|applicable)\b/i],
  },
  {
    standardParameter: 'Reverse Auction',
    canonicalKey: 'reverseAuction',
    category: 'Tender Specific',
    priority: 65,
    aliases: ['Reverse Auction', 'RA Applicable', 'E-Reverse Auction', 'Reverse Bidding'],
    patterns: [/\breverse\s*auction\b/i, /\breverse\s*bidd?ing\b/i],
  },
  {
    standardParameter: 'Work Order Requirement',
    canonicalKey: 'workOrders',
    category: 'Experience',
    priority: 75,
    aliases: ['Work Order Requirement', 'Work Orders', 'Work Order', 'Purchase Order', 'PO Copies'],
    patterns: [/\bwork\s*orders?(\s*requirement)?\b/i],
  },
  {
    standardParameter: 'Completion Certificate Requirement',
    canonicalKey: 'completionCertificates',
    category: 'Experience',
    priority: 75,
    aliases: [
      'Completion Certificate Requirement',
      'Completion Certificate',
      'Completion Certificates',
      'Work Completion Certificate',
    ],
    patterns: [/\bcompletion\s*certificates?(\s*requirement)?\b/i],
  },
  {
    standardParameter: 'Experience Certificate Requirement',
    canonicalKey: 'experienceCertificates',
    category: 'Experience',
    priority: 75,
    aliases: [
      'Experience Certificate Requirement',
      'Experience Certificate',
      'Experience Certificates',
      'Work Experience Certificate',
    ],
    patterns: [/\bexperience\s*certificates?(\s*requirement)?\b/i],
  },
];

/** Convert registry entries to legacy catalog shape for backward compatibility. */
export function toLegacyAliasCatalogDefinitions() {
  return MASTER_ALIAS_REGISTRY.filter((entry) => entry.canonicalKey).map((entry) => ({
    canonical: entry.standardParameter,
    canonicalKey: entry.canonicalKey!,
    aliases: entry.aliases.map((a) => a.toLowerCase()),
    patterns: entry.patterns ?? [],
  }));
}

export function formatMasterAliasRegistryForPrompt(limit = 50): string {
  return MASTER_ALIAS_REGISTRY.slice(0, limit)
    .flatMap((e) => e.aliases.slice(0, 6).map((a) => `${a} → ${e.standardParameter}`))
    .join('\n');
}
