import { TenderDocumentSectionType } from '../../types/tenderIntelligenceLayer';

export interface EnterpriseSectionDefinition {
  section: TenderDocumentSectionType;
  keywords: string[];
  headingPatterns: RegExp[];
  tableTitlePatterns: RegExp[];
}

/** Enterprise section knowledge base — keywords, headings, and table titles. */
export const ENTERPRISE_SECTION_KNOWLEDGE_BASE: EnterpriseSectionDefinition[] = [
  {
    section: 'Identity',
    keywords: [
      'tender number',
      'nit number',
      'nit no',
      'e-tender',
      'eprocurement',
      'organization',
      'organisation',
      'department',
      'tender title',
      'name of work',
      'inviting authority',
      'tender reference',
      'bid reference',
      'location',
      'place of work',
      'issuing authority',
    ],
    headingPatterns: [
      /notice\s+inviting\s+tender/i,
      /\bnit\b/i,
      /tender\s+notice/i,
      /general\s+information/i,
      /tender\s+particulars/i,
      /particulars\s+of\s+tender/i,
    ],
    tableTitlePatterns: [/tender\s+details/i, /nit\s+details/i, /general\s+particulars/i],
  },
  {
    section: 'Financial',
    keywords: [
      'tender value',
      'estimated cost',
      'project cost',
      'contract value',
      'earnest money',
      'emd',
      'tender fee',
      'document fee',
      'bid security',
      'security deposit',
      'performance security',
      'performance guarantee',
      'bank guarantee',
      'payment terms',
      'price bid',
      'financial bid',
    ],
    headingPatterns: [
      /financial\s+(?:bid|particulars|conditions?)/i,
      /earnest\s+money/i,
      /\bemd\b/i,
      /tender\s+fee/i,
      /cost\s+of\s+tender/i,
    ],
    tableTitlePatterns: [/financial\s+summary/i, /fee\s+details/i, /emd\s+details/i],
  },
  {
    section: 'Timeline',
    keywords: [
      'publishing date',
      'pre-bid',
      'pre bid',
      'bid start',
      'bid end',
      'last date',
      'submission deadline',
      'bid opening',
      'technical opening',
      'financial opening',
      'completion period',
      'contract period',
      'time schedule',
      'important dates',
      'schedule of dates',
    ],
    headingPatterns: [
      /important\s+dates?/i,
      /schedule\s+of\s+(?:dates|bid)/i,
      /bid\s+schedule/i,
      /time\s+schedule/i,
      /key\s+dates/i,
    ],
    tableTitlePatterns: [/date\s+schedule/i, /bid\s+timeline/i],
  },
  {
    section: 'Eligibility',
    keywords: [
      'eligibility',
      'qualification criteria',
      'pre-qualification',
      'turnover',
      'annual turnover',
      'experience requirement',
      'net worth',
      'bid capacity',
      'manpower requirement',
      'minimum qualification',
      'bidder eligibility',
    ],
    headingPatterns: [
      /eligibility\s+criteria/i,
      /qualification\s+criteria/i,
      /pre[\s-]?qualification/i,
      /qualifying\s+requirements/i,
    ],
    tableTitlePatterns: [/eligibility\s+table/i, /qualification\s+requirements/i],
  },
  {
    section: 'Compliance',
    keywords: [
      'gst',
      'pan',
      'msme',
      'epf',
      'esic',
      'pf registration',
      'esi registration',
      'labour license',
      'labour licence',
      'iso certification',
      'bank solvency',
      'statutory compliance',
      'declaration',
      'integrity pact',
    ],
    headingPatterns: [
      /compliance\s+requirements?/i,
      /statutory\s+requirements?/i,
      /legal\s+requirements?/i,
      /\bgst\b/i,
      /registration\s+requirements/i,
    ],
    tableTitlePatterns: [/compliance\s+checklist/i, /statutory\s+documents/i],
  },
  {
    section: 'Experience',
    keywords: [
      'work order',
      'completion certificate',
      'experience certificate',
      'past projects',
      'similar work',
      'client reference',
      'past performance',
      'completed projects',
      'proof of experience',
    ],
    headingPatterns: [
      /experience\s+requirements?/i,
      /similar\s+works?/i,
      /past\s+experience/i,
      /work\s+experience/i,
    ],
    tableTitlePatterns: [/experience\s+details/i, /list\s+of\s+works/i],
  },
  {
    section: 'Scope',
    keywords: [
      'scope of work',
      'scope of services',
      'deliverables',
      'deployment',
      'activities',
      'responsibilities',
      'nature of work',
      'statement of work',
      'services to be provided',
      'job description',
    ],
    headingPatterns: [
      /scope\s+of\s+(?:work|services?|contract)/i,
      /statement\s+of\s+work/i,
      /nature\s+of\s+work/i,
      /description\s+of\s+(?:work|services)/i,
    ],
    tableTitlePatterns: [/scope\s+summary/i, /deliverables/i],
  },
  {
    section: 'Technical Specifications',
    keywords: [
      'technical specification',
      'technical requirements',
      'technical bid',
      'equipment',
      'machinery',
      'software',
      'hardware',
      'network',
      'performance standards',
      'make and model',
      'technical compliance',
    ],
    headingPatterns: [
      /technical\s+specifications?/i,
      /technical\s+requirements?/i,
      /technical\s+bid/i,
      /equipment\s+specification/i,
    ],
    tableTitlePatterns: [/technical\s+data/i, /specification\s+sheet/i],
  },
  {
    section: 'Tender Specific',
    keywords: [
      'maf',
      'oem authorization',
      'oem authorisation',
      'reverse auction',
      'make in india',
      'mse preference',
      'gem conditions',
      'psara',
      'special conditions',
      'particular conditions',
      'purchase preference',
      'ebg',
      'epbg',
    ],
    headingPatterns: [
      /special\s+conditions?/i,
      /particular\s+conditions?/i,
      /tender\s+specific/i,
      /make\s+in\s+india/i,
      /reverse\s+auction/i,
    ],
    tableTitlePatterns: [/special\s+requirements/i, /gem\s+conditions/i],
  },
  {
    section: 'Annexures',
    keywords: [
      'annexure',
      'appendix',
      'enclosure',
      'form no',
      'format no',
      'undertaking',
      'integrity pact',
      'declaration form',
      'bid form',
      'proforma',
      'specimen format',
    ],
    headingPatterns: [
      /^annexure\s+[a-z0-9ivxlc]+/im,
      /^appendix\s+[a-z0-9ivxlc]+/im,
      /integrity\s+pact/i,
      /undertaking/i,
      /declaration\s+form/i,
      /bid\s+form/i,
    ],
    tableTitlePatterns: [/form\s+for/i, /format\s+for/i],
  },
];

/** Neighboring sections searched when primary section has no match (never Annexures first). */
export const SECTION_NEIGHBOR_MAP: Record<TenderDocumentSectionType, TenderDocumentSectionType[]> = {
  Identity: ['Financial', 'Timeline'],
  Financial: ['Identity', 'Timeline', 'Tender Specific'],
  Timeline: ['Financial', 'Identity'],
  Eligibility: ['Experience', 'Compliance', 'Financial'],
  Compliance: ['Eligibility', 'Experience'],
  Experience: ['Eligibility', 'Compliance'],
  Scope: ['Technical Specifications', 'Tender Specific'],
  'Technical Specifications': ['Scope', 'Tender Specific'],
  'Tender Specific': ['Scope', 'Financial', 'Compliance'],
  Annexures: [],
};

export function getSectionNeighborFallbacks(
  section: TenderDocumentSectionType
): TenderDocumentSectionType[] {
  return SECTION_NEIGHBOR_MAP[section] || [];
}

export function getEnterpriseSectionDefinitions(): EnterpriseSectionDefinition[] {
  return ENTERPRISE_SECTION_KNOWLEDGE_BASE;
}
