import {
  TenderTypeAliasMapping,
  TenderTypeIntelligenceType,
  TenderTypeProfile,
} from '../../types/tenderTypeIntelligence';

export interface TenderTypeProfileDefinition {
  type: TenderTypeIntelligenceType;
  keywords: string[];
  headingPatterns?: RegExp[];
  parameters: string[];
  /** Subset of parameters to prioritize during type-specific extraction search. */
  searchParameters?: string[];
  rules: string[];
  aliases: TenderTypeAliasMapping[];
}

export const TENDER_TYPE_PROFILE_KNOWLEDGE_BASE: TenderTypeProfileDefinition[] = [
  {
    type: 'GeM',
    keywords: [
      'government e marketplace',
      'government e-marketplace',
      'gem portal',
      'bid on gem',
      'gem bid',
      'gem contract',
      'www.gem.gov.in',
      'gem.gov.in',
      'e marketplace',
    ],
    headingPatterns: [/\bgem\b/i, /government\s+e[\s-]?marketplace/i],
    parameters: [
      'GeM Bid Number',
      'Bid Type',
      'Evaluation Method',
      'BOQ Type',
      'MSE Preference',
      'Make In India Preference',
      'Startup Preference',
      'Purchase Preference',
      'ePBG Percentage',
      'Buyer Added Bid Specific ATC',
      'OEM Authorization',
      'Experience Criteria',
      'Turnover Criteria',
      'GeM Category',
      'MII Preference',
    ],
    searchParameters: [
      'GeM Bid Number',
      'Bid Type',
      'Evaluation Method',
      'BOQ Type',
      'MSE Preference',
      'Make In India Preference',
      'Startup Preference',
      'Purchase Preference',
      'ePBG Percentage',
      'Buyer Added Bid Specific ATC',
      'OEM Authorization',
      'Experience Criteria',
      'Turnover Criteria',
    ],
    rules: [
      'Load GeM Library — only then search for ePBG, MSE, Make In India, Purchase Preference.',
      'Prefer GeM-specific financial fields: ePBG Percentage over generic PBG when both appear.',
      'Extract Bid Type (Two Packet / Single Packet / RA) and Evaluation Method when present.',
      'Capture MSE/MII/Startup/Purchase Preference as yes/no or stated policy text.',
      'Extract BOQ Type and Buyer Added Bid Specific ATC when labeled in GeM bid documents.',
    ],
    aliases: [
      { from: ['ePBG', 'ePBG Percentage', 'Electronic Performance Bank Guarantee', 'Performance Bank Guarantee GeM'], to: 'ePBG Percentage' },
      { from: ['MSE', 'MSME Preference', 'Micro and Small Enterprise', 'MSE Preference'], to: 'MSE Preference' },
      { from: ['Make In India', 'MII', 'MII Preference', 'Make In India Preference'], to: 'Make In India Preference' },
      { from: ['Startup Preference', 'Startup India Preference'], to: 'Startup Preference' },
      { from: ['Purchase Preference', 'Local Content Preference'], to: 'Purchase Preference' },
      { from: ['Bid Type', 'Type of Bid'], to: 'Bid Type' },
      { from: ['GeM Bid Number', 'Bid Number GeM', 'GeM Bid No'], to: 'GeM Bid Number' },
      { from: ['Evaluation Method', 'Bid Evaluation Method'], to: 'Evaluation Method' },
      { from: ['BOQ Type', 'Bill of Quantity Type'], to: 'BOQ Type' },
      { from: ['ATC', 'Buyer Added Bid Specific ATC', 'Additional Terms and Conditions'], to: 'Buyer Added Bid Specific ATC' },
    ],
  },
  {
    type: 'CPWD',
    keywords: [
      'cpwd',
      'central public works department',
      'directorate general of works',
      'dgw',
      'works contract cpwd',
      'cpwd tender',
      'as per cpwd',
    ],
    headingPatterns: [/\bcpwd\b/i, /central\s+public\s+works/i],
    parameters: [
      'NIT Number',
      'Estimated Cost',
      'EMD',
      'Tender Fee',
      'Completion Period',
      'Performance Guarantee',
      'Security Deposit',
      'Defect Liability Period',
      'Similar Work Criteria',
      'Turnover Requirement',
      'Technical Staff Requirement',
      'Machinery Requirement',
      'SCHEDULE OF RATES',
      'DAR',
      'Labour Cess',
      'Contractor Registration CPWD',
    ],
    searchParameters: [
      'NIT Number',
      'Estimated Cost',
      'EMD',
      'Tender Fee',
      'Completion Period',
      'Performance Guarantee',
      'Security Deposit',
      'Defect Liability Period',
      'Similar Work Criteria',
      'Turnover Requirement',
      'Technical Staff Requirement',
      'Machinery Requirement',
    ],
    rules: [
      'Load CPWD Library — prioritize NIT Number, Estimated Cost, EMD, Security Deposit, DLP.',
      'CPWD tenders often reference DAR/SOR — extract deviation and rate schedule references.',
      'Security Deposit and Performance Guarantee may appear with CPWD-specific percentages.',
      'Extract Similar Work Criteria and Technical Staff Requirement from eligibility sections.',
    ],
    aliases: [
      { from: ['NIT Number', 'NIT No', 'Notice Inviting Tender No'], to: 'NIT Number' },
      { from: ['Estimated Cost', 'Estimated Cost of Work', 'Tender Value'], to: 'Estimated Cost' },
      { from: ['EMD', 'Earnest Money Deposit', 'Bid Security'], to: 'EMD' },
      { from: ['Security Deposit', 'SD Amount'], to: 'Security Deposit' },
      { from: ['DLP', 'Defect Liability Period'], to: 'Defect Liability Period' },
      { from: ['Performance Guarantee', 'PBG', 'Performance Bank Guarantee'], to: 'Performance Guarantee' },
      { from: ['Similar Work', 'Similar Work Criteria', 'Similar Work Experience'], to: 'Similar Work Criteria' },
    ],
  },
  {
    type: 'Manpower',
    keywords: [
      'manpower supply',
      'deployment of manpower',
      'contract labour',
      'skilled manpower',
      'unskilled manpower',
      'outsourcing of manpower',
      'human resource',
      'staff deployment',
      'labour supply',
      'payroll',
    ],
    headingPatterns: [/manpower/i, /contract\s+labou?r/i, /staff\s+deployment/i],
    parameters: [
      'Manpower Requirement',
      'Payroll Strength',
      'Minimum Employees',
      'EPF',
      'ESIC',
      'Labour License',
      'Minimum Wages Compliance',
      'Supervisor Count',
      'Operator Count',
      'Helper Count',
      'Shift Requirement',
      'Deployment Requirement',
      'Contract Labour License',
      'Uniform Requirement',
    ],
    searchParameters: [
      'Manpower Requirement',
      'Payroll Strength',
      'Minimum Employees',
      'EPF',
      'ESIC',
      'Labour License',
      'Minimum Wages Compliance',
      'Supervisor Count',
      'Operator Count',
      'Helper Count',
      'Shift Requirement',
      'Deployment Requirement',
    ],
    rules: [
      'Load Manpower Library — only then search for EPF, ESIC, Payroll Strength, Minimum Wages.',
      'Extract headcount by role when manpower tables are present.',
      'Capture statutory compliance: EPF, ESIC, Minimum Wages Act, Labour License.',
      'Payroll strength must be numeric or role-wise count, not prose.',
    ],
    aliases: [
      { from: ['EPF', 'Provident Fund', 'PF Contribution', 'Employees Provident Fund'], to: 'EPF' },
      { from: ['ESIC', 'ESI', 'Employees State Insurance'], to: 'ESIC' },
      { from: ['Labour License', 'Contract Labour Act License', 'CLRA License'], to: 'Labour License' },
      { from: ['Minimum Wages', 'Min Wages', 'Minimum Wage Rate', 'Minimum Wages Compliance'], to: 'Minimum Wages Compliance' },
      { from: ['Payroll Strength', 'Employee Strength', 'Minimum Employees', 'Manpower Strength'], to: 'Payroll Strength' },
      { from: ['Manpower Count', 'Manpower Requirement', 'Staff Deployment'], to: 'Manpower Requirement' },
    ],
  },
  {
    type: 'Security',
    keywords: [
      'security services',
      'security guard',
      'guarding services',
      'watch and ward',
      'psara',
      'private security agency',
      'cctv surveillance',
      'armed guard',
      'unarmed guard',
      'control room',
    ],
    headingPatterns: [/security\s+services?/i, /guarding/i, /watch\s+and\s+ward/i],
    parameters: [
      'PSARA',
      'Security Guards',
      'Armed Guards',
      'Unarmed Guards',
      'Supervisors',
      'Control Room',
      'Gun License',
      'Quick Response Team',
      'Patrolling Requirement',
      'Deployment Strength',
      'PSARA License',
      'CCTV Requirement',
      'Ex-Servicemen Requirement',
    ],
    searchParameters: [
      'PSARA',
      'Security Guards',
      'Armed Guards',
      'Unarmed Guards',
      'Supervisors',
      'Control Room',
      'Gun License',
      'Quick Response Team',
      'Patrolling Requirement',
      'Deployment Strength',
    ],
    rules: [
      'Load Security Library — only then search for PSARA, Armed Guards, Deployment Strength.',
      'PSARA license validity and state registration are mandatory compliance fields.',
      'Extract guard counts by category: armed, unarmed, supervisor, control room operator.',
      'Patrolling and QRT requirements are scope parameters when explicitly stated.',
    ],
    aliases: [
      { from: ['PSARA', 'PSARA License', 'Private Security Agency Regulation Act'], to: 'PSARA' },
      { from: ['Armed Guard', 'Armed Guards', 'Armed Security Guard', 'Gunman'], to: 'Armed Guards' },
      { from: ['Unarmed Guard', 'Unarmed Guards', 'Security Guard'], to: 'Unarmed Guards' },
      { from: ['Security Supervisor', 'Supervisor Security', 'Supervisors'], to: 'Supervisors' },
      { from: ['Control Room', 'CCTV Control Room'], to: 'Control Room' },
      { from: ['Gun License', 'Weapon License', 'Arms License'], to: 'Gun License' },
      { from: ['QRT', 'Quick Response Team'], to: 'Quick Response Team' },
      { from: ['Deployment Strength', 'Guard Strength', 'Security Personnel Count'], to: 'Deployment Strength' },
    ],
  },
  {
    type: 'Housekeeping',
    keywords: [
      'housekeeping',
      'cleaning services',
      'sanitation services',
      'janitorial',
      'sweeper',
      'mopping',
      'deep cleaning',
      'house keeping',
    ],
    headingPatterns: [/housekeeping/i, /cleaning\s+services?/i],
    parameters: [
      'Housekeeping Staff',
      'Cleaning Equipment',
      'Consumables',
      'Deployment Schedule',
      'Supervisor Requirement',
      'Cleaning Area',
      'Housekeeping Staff Count',
      'Machine Cleaning',
      'Toilet Maintenance',
      'Floor Cleaning Frequency',
    ],
    searchParameters: [
      'Housekeeping Staff',
      'Cleaning Equipment',
      'Consumables',
      'Deployment Schedule',
      'Supervisor Requirement',
      'Cleaning Area',
    ],
    rules: [
      'Load Housekeeping Library — prioritize staff count, cleaning area, consumables, deployment schedule.',
      'Extract staff strength by shift and location when available.',
      'Consumables and equipment requirements are valid dynamic parameters.',
    ],
    aliases: [
      { from: ['HK Staff', 'Housekeeping Staff', 'House Keeping Staff', 'Housekeeping Staff Count'], to: 'Housekeeping Staff' },
      { from: ['Cleaning Staff', 'Janitorial Staff'], to: 'Housekeeping Staff' },
      { from: ['Cleaning Material', 'Cleaning Equipment'], to: 'Cleaning Equipment' },
      { from: ['Supervisor Housekeeping', 'Supervisor Requirement'], to: 'Supervisor Requirement' },
    ],
  },
  {
    type: 'Facility Management',
    keywords: [
      'facility management',
      'integrated facility',
      'fm services',
      'building maintenance',
      'estate management',
      'soft services',
      'hard services',
      'integrated fm',
    ],
    headingPatterns: [/facility\s+management/i, /integrated\s+facility/i],
    parameters: [
      'Soft Services Scope',
      'Hard Services Scope',
      'Helpdesk SLA',
      'Asset Management',
      'PPM Schedule',
      'Energy Management',
      'Waste Management',
    ],
    rules: [
      'Separate soft services (HK, pantry, landscaping) from hard services (MEP, civil).',
      'Extract SLA response times when stated.',
    ],
    aliases: [
      { from: ['FM Services', 'Integrated FM', 'IFM'], to: 'Facility Management Scope' },
      { from: ['PPM', 'Preventive Maintenance Plan'], to: 'PPM Schedule' },
    ],
  },
  {
    type: 'Civil',
    keywords: [
      'civil works',
      'construction work',
      'building work',
      'road work',
      'structural work',
      'rcc work',
      'earthwork',
      'brick work',
    ],
    headingPatterns: [/civil\s+works?/i, /construction/i],
    parameters: [
      'Concrete Grade',
      'Steel Grade',
      'BOQ Item Count',
      'Site Handover Date',
      'Mobilization Period',
      'Quality Assurance Plan',
    ],
    rules: [
      'Extract BOQ-related quantities and grades when explicitly labeled.',
      'Mobilization and completion milestones are timeline parameters.',
    ],
    aliases: [
      { from: ['Grade of Concrete', 'M Grade', 'Concrete M'], to: 'Concrete Grade' },
      { from: ['Mobilization', 'Mobilisation Period'], to: 'Mobilization Period' },
    ],
  },
  {
    type: 'Electrical',
    keywords: [
      'electrical works',
      'electrical installation',
      'wiring',
      'lt panel',
      'ht panel',
      'electrification',
      'substation',
      'electrical maintenance',
    ],
    headingPatterns: [/electrical\s+works?/i, /electrification/i],
    parameters: [
      'Transformer',
      'Substation',
      'HT Panel',
      'LT Panel',
      'Electrical Contractor License',
      'Testing Equipment',
      'Connected Load',
      'Contract Demand',
      'Earthing Requirement',
      'Electrical Safety Audit',
    ],
    searchParameters: [
      'Transformer',
      'Substation',
      'HT Panel',
      'LT Panel',
      'Electrical Contractor License',
      'Testing Equipment',
    ],
    rules: [
      'Load Electrical Library — prioritize transformer, substation, HT/LT panel specifications.',
      'Extract load/capacity values with units (kW, kVA).',
      'Electrical Contractor License is a compliance parameter when stated.',
    ],
    aliases: [
      { from: ['HT Panel', 'High Tension Panel'], to: 'HT Panel' },
      { from: ['LT Panel', 'Low Tension Panel'], to: 'LT Panel' },
      { from: ['Connected Load', 'Sanctioned Load'], to: 'Connected Load' },
      { from: ['CD', 'Contract Demand'], to: 'Contract Demand' },
      { from: ['Electrical License', 'Electrical Contractor License'], to: 'Electrical Contractor License' },
    ],
  },
  {
    type: 'Mechanical',
    keywords: [
      'mechanical works',
      'hvac',
      'air conditioning',
      'chiller',
      'boiler',
      'pump installation',
      'mechanical maintenance',
      'ventilation',
    ],
    headingPatterns: [/mechanical\s+works?/i, /\bhvac\b/i],
    parameters: [
      'HVAC Capacity',
      'Chiller TR',
      'AMC Period',
      'Spare Parts',
      'Cooling Tower',
      'Compressor Make',
    ],
    rules: [
      'HVAC capacity must include TR/tonnage or CFM when present.',
      'AMC and warranty periods are valid timeline parameters.',
    ],
    aliases: [
      { from: ['TR Capacity', 'Tonnage of Refrigeration', 'Chiller Capacity'], to: 'Chiller TR' },
      { from: ['AMC', 'Annual Maintenance Contract'], to: 'AMC Period' },
    ],
  },
  {
    type: 'IT',
    keywords: [
      'it services',
      'software development',
      'hardware supply',
      'data center',
      'cloud services',
      'networking',
      'system integration',
      'erp implementation',
      'information technology',
    ],
    headingPatterns: [/it\s+services?/i, /software/i, /system\s+integration/i],
    parameters: [
      'OEM Authorization',
      'MAF',
      'Warranty',
      'AMC',
      'SLA',
      'Data Center',
      'Cloud Certification',
      'Network Requirement',
      'Server Requirement',
      'Cyber Security Requirement',
      'SLA Uptime',
      'Response Time',
      'License Count',
      'Implementation Period',
    ],
    searchParameters: [
      'OEM Authorization',
      'MAF',
      'Warranty',
      'AMC',
      'SLA',
      'Data Center',
      'Cloud Certification',
      'Network Requirement',
      'Server Requirement',
      'Cyber Security Requirement',
    ],
    rules: [
      'Load IT Library — prioritize OEM Authorization, MAF, SLA, AMC, cloud and security requirements.',
      'Extract SLA metrics as numeric/time-bound values.',
      'License count and user count are valid count parameters.',
    ],
    aliases: [
      { from: ['OEM Authorization', 'OEM Certificate', 'Manufacturer Authorization'], to: 'OEM Authorization' },
      { from: ['MAF', 'Manufacturer Authorization Form'], to: 'MAF' },
      { from: ['Warranty Period', 'Warranty'], to: 'Warranty' },
      { from: ['AMC', 'Annual Maintenance Contract', 'AMC Duration'], to: 'AMC' },
      { from: ['Uptime SLA', 'Availability SLA', 'SLA'], to: 'SLA' },
      { from: ['Data Centre', 'Data Center Requirement'], to: 'Data Center' },
      { from: ['Cyber Security', 'Cybersecurity Requirement', 'Information Security'], to: 'Cyber Security Requirement' },
    ],
  },
  {
    type: 'Procurement',
    keywords: [
      'supply of goods',
      'procurement of goods',
      'purchase of',
      'supply order',
      'rate contract',
      'goods tender',
      'material supply',
      'procurement notice',
      'purchase preference',
    ],
    headingPatterns: [/supply\s+of/i, /procurement\s+of/i, /purchase\s+of/i],
    parameters: [
      'Delivery Period',
      'Make and Model',
      'OEM Authorization',
      'Warranty Period',
      'Inspection Requirement',
      'Quantity',
      'Unit Rate',
      'Delivery Location',
    ],
    rules: [
      'Extract item-wise quantity and delivery period when in supply schedules.',
      'OEM authorization and warranty are common procurement compliance fields.',
    ],
    aliases: [
      { from: ['Delivery Schedule', 'Delivery Period', 'Delivery Time'], to: 'Delivery Period' },
      { from: ['Make & Model', 'Brand and Model'], to: 'Make and Model' },
      { from: ['MAF', 'Manufacturer Authorization Form'], to: 'OEM Authorization' },
    ],
  },
  {
    type: 'Railway',
    keywords: [
      'indian railways',
      'railway board',
      'irctc',
      'railway tender',
      'railway administration',
      'zonal railway',
      'divisional railway',
      'railway workshop',
    ],
    headingPatterns: [/indian\s+railways?/i, /railway\s+board/i],
    parameters: [
      'Railway Experience',
      'Vendor Registration',
      'RDSO Approval',
      'Railway Standards',
      'Railway Zone',
      'Division',
      'Depot Code',
      'RDSO Specification',
      'Inspection by Railway',
    ],
    searchParameters: [
      'Railway Experience',
      'Vendor Registration',
      'RDSO Approval',
      'Railway Standards',
      'Railway Zone',
      'Division',
    ],
    rules: [
      'Load Railway Library — prioritize Railway Experience, Vendor Registration, RDSO Approval.',
      'Railway tenders may reference RDSO specifications — extract when labeled.',
      'Zone/division/depot identity fields are high priority.',
    ],
    aliases: [
      { from: ['Zone', 'Railway Zone'], to: 'Railway Zone' },
      { from: ['RDSO Spec', 'RDSO Specification', 'RDSO Approval'], to: 'RDSO Approval' },
      { from: ['Railway Experience', 'Experience with Indian Railways'], to: 'Railway Experience' },
      { from: ['Vendor Registration', 'Railway Vendor Registration'], to: 'Vendor Registration' },
    ],
  },
  {
    type: 'Healthcare',
    keywords: [
      'hospital services',
      'medical equipment',
      'healthcare',
      'diagnostic services',
      'pharmacy',
      'patient care',
      'biomedical',
      'clinical',
    ],
    headingPatterns: [/healthcare/i, /hospital\s+services?/i, /medical\s+equipment/i],
    parameters: [
      'Medical Staff',
      'Hospital Experience',
      'NABH',
      'Medical Equipment',
      'Patient Support Services',
      'Biomedical Waste Management',
      'Calibration Certificate',
      'CDSCO Registration',
      'Sterilization Requirement',
    ],
    searchParameters: [
      'Medical Staff',
      'Hospital Experience',
      'NABH',
      'Medical Equipment',
      'Patient Support Services',
    ],
    rules: [
      'Load Healthcare Library — prioritize Medical Staff, Hospital Experience, NABH accreditation.',
      'Medical equipment tenders require CDSCO/ISO calibration references when present.',
      'Biomedical waste and sterilization are compliance parameters.',
    ],
    aliases: [
      { from: ['NABH', 'NABH Accreditation', 'NABH Certified'], to: 'NABH' },
      { from: ['Medical Staff', 'Clinical Staff', 'Healthcare Staff'], to: 'Medical Staff' },
      { from: ['Hospital Experience', 'Healthcare Experience'], to: 'Hospital Experience' },
      { from: ['BMW', 'Biomedical Waste', 'Bio Medical Waste'], to: 'Biomedical Waste Management' },
      { from: ['CDSCO', 'Drug License'], to: 'CDSCO Registration' },
    ],
  },
  {
    type: 'Education',
    keywords: [
      'school services',
      'education department',
      'academic services',
      'teaching staff',
      'educational institution',
      'university tender',
      'college tender',
      'mid day meal',
      'smart classroom',
    ],
    headingPatterns: [/education\s+department/i, /school\s+services?/i, /academic/i],
    parameters: [
      'Teaching Staff Requirement',
      'Non-Teaching Staff',
      'Student Strength',
      'Academic Qualification',
      'Lab Equipment',
      'Library Services',
      'Smart Classroom',
      'Mid Day Meal',
    ],
    searchParameters: [
      'Teaching Staff Requirement',
      'Non-Teaching Staff',
      'Student Strength',
      'Academic Qualification',
      'Lab Equipment',
    ],
    rules: [
      'Load Education Library — prioritize teaching/non-teaching staff counts and academic qualifications.',
      'Extract lab equipment and library service requirements when explicitly stated.',
    ],
    aliases: [
      { from: ['Teaching Staff', 'Teacher Requirement'], to: 'Teaching Staff Requirement' },
      { from: ['Non Teaching Staff', 'Support Staff'], to: 'Non-Teaching Staff' },
    ],
  },
  {
    type: 'Consultancy',
    keywords: [
      'consultancy services',
      'consulting services',
      'technical consultancy',
      'management consultancy',
      'feasibility study',
      'design consultancy',
      'architectural consultancy',
      'project management consultant',
      'pmc',
    ],
    headingPatterns: [/consultancy\s+services?/i, /consulting\s+services?/i, /\bpmc\b/i],
    parameters: [
      'Consultant Qualification',
      'Key Personnel',
      'Experience in Similar Assignments',
      'Methodology',
      'Deliverables',
      'Timeline of Assignment',
      'Fee Structure',
      'Conflict of Interest Declaration',
    ],
    searchParameters: [
      'Consultant Qualification',
      'Key Personnel',
      'Experience in Similar Assignments',
      'Methodology',
      'Deliverables',
      'Timeline of Assignment',
    ],
    rules: [
      'Load Consultancy Library — prioritize key personnel, similar assignment experience, deliverables.',
      'Extract consultant qualification and methodology when labeled in RFP documents.',
    ],
    aliases: [
      { from: ['Key Personnel', 'Key Expert', 'Team Leader'], to: 'Key Personnel' },
      { from: ['Similar Assignments', 'Similar Consultancy Experience'], to: 'Experience in Similar Assignments' },
      { from: ['PMC', 'Project Management Consultant'], to: 'Key Personnel' },
    ],
  },
];

export function getTenderTypeProfile(tenderType: string): TenderTypeProfile {
  const def = TENDER_TYPE_PROFILE_KNOWLEDGE_BASE.find((d) => d.type === tenderType);
  if (!def) {
    return { tenderType: '', parameters: [], rules: [], aliases: [] };
  }
  return {
    tenderType: def.type,
    parameters: def.parameters,
    rules: def.rules,
    aliases: def.aliases,
  };
}

export function getTenderTypeProfileDefinitions(): TenderTypeProfileDefinition[] {
  return TENDER_TYPE_PROFILE_KNOWLEDGE_BASE;
}
